### ISSUE TITLE
Database Design and Schema

### ISSUE THREAD

**Issue by kingm14cs** [ZhihengChang/iManager#26]
Create, design, and implement a database schema

**Comment by kingm14cs** [comment]
![imanager](https://user-images.githubusercontent.com/44519099/110698772-1325a100-81bc-11eb-8e14-d779b51d7c02.png)

**Comment by ZhihengChang** [comment]
documentation link: https://docs.google.com/document/d/1E875GsDo-yUfS72NDu1vRUAR2puxNzVSJrEGGSVgZ4A/edit
